apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: webhook
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h
    receivers:
      - name: webhook
        webhook_configs:
          - url: "https://webhook.site/fbcc6e3e-fac8-40fa-b876-52f5cb2d49f5"
            send_resolved: true